### ISSUE TITLE
upgrade required node version to 12+

### ISSUE THREAD

**Issue by g-k** [mozilla-services/ip-reputation-js-client#37]
Staying on node 8 is probably going to limit how up to date we can keep our deps and how much FxA can de-dup.

FxA is the only consumer of this library AFAIK. They're on 12 for dev https://github.com/mozilla/fxa#installing-nodejs , but I'm not sure about prod.

**Comment by vladikoff** [comment]
@g-k prod is also on 12, per https://github.com/mozilla/fxa/blob/master/.circleci/config.yml#L34
